/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package write.your.own.jvm;

import write.your.own.jvm.classfile.ClassFile;
import write.your.own.jvm.classfile.MemberInfo;
import write.your.own.jvm.classfile.constantpool.ConstantInfo;
import write.your.own.jvm.classfile.constantpool.ConstantPool;
import write.your.own.jvm.classpath.Classpath;
import write.your.own.jvm.runtimedata.heap.MyClass;
import write.your.own.jvm.runtimedata.heap.MyClassLoader;
import write.your.own.jvm.util.Log;

public class Main {
    public static void main(String[] args) {
        Cmd cmd = Cmd.parseArgs(args);
        printArgs(cmd);
        startJvm(cmd);
    }

    private static void startJvm(Cmd cmd) {
        Classpath classpath = new Classpath("", cmd.getClasspath());
        String className = cmd.getMainClass().replace(".", "/");
        MyClassLoader classLoader = new MyClassLoader(classpath);
        try {
            MyClass mainClass = classLoader.loadClass(className);
            Interpreter interpreter = new Interpreter();
            interpreter.interpret(mainClass.geMainMethod());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private static MemberInfo getMethod(ClassFile classFile, String name, String des) {
        MemberInfo[] methods = classFile.getMethods();
        for (MemberInfo method : methods) {
            if (method.getName().equals(name)
                    && method.getDescriptor().equals(des)) {
                return method;
            }
        }

        return null;
    }

    private static void printClassInfo(ClassFile classFile) {
        Log.o("version: " + classFile.getMajorVersion() + "." + classFile.getMinorVersion());

        ConstantPool constantPool = classFile.getConstantPool();
        ConstantInfo[] constantInfos = constantPool.getConstantInfos();
        Log.o("constants count: " + constantPool.getSize());
        for (int i = 1; i < constantPool.getSize(); i++) {
            if (constantInfos[i] != null) {
                Log.o(i + ": " + constantInfos[i]);
            }
        }

        Log.o("access flags: 0x" + classFile.getAccessFlag());
        Log.o("this class: " + constantPool.getUtf8(classFile.getThisClassIndex()));
        Log.o("super class: " + constantPool.getUtf8(classFile.getSuperClassIndex()));
        Log.o("interfaces: " + classFile.getInterfaceIndexes().length);
        MemberInfo[] fields = classFile.getFields();
        Log.o("fields count: " + fields.length);
        for (MemberInfo memberInfo : fields) {
            Log.o("  " + constantPool.getUtf8(memberInfo.getNameIndex()));
        }

        MemberInfo[] methods = classFile.getMethods();
        Log.o("methods count: " + methods.length);
        for (MemberInfo memberInfo : methods) {
            Log.o("  " + constantPool.getUtf8(memberInfo.getNameIndex()));
        }
    }

    private static void printArgs(Cmd cmd) {
        Log.o("main class: " + cmd.getMainClass());
        Log.o("args: " + cmd.getArgs().toString());
    }
}
