/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package write.your.own.jvm;

import write.your.own.jvm.classpath.Classpath;
import write.your.own.jvm.runtimedata.heap.MyClass;
import write.your.own.jvm.runtimedata.heap.MyClassLoader;
import write.your.own.jvm.util.Log;
import write.your.own.jvm.vnative.NativeRegistry;

public class Main {
    public static void main(String[] args) {
        Cmd cmd = Cmd.parseArgs(args);
        printArgs(cmd);
        startJvm(cmd);
    }

    private static void startJvm(Cmd cmd) {
        Classpath classpath = new Classpath("", cmd.getClasspath());
        String className = cmd.getMainClass().replace(".", "/");
        MyClassLoader classLoader = new MyClassLoader(classpath);
        NativeRegistry.init();
        try {
            MyClass mainClass = classLoader.loadClass(className);
            Interpreter interpreter = new Interpreter();
            interpreter.interpret(mainClass.geMainMethod(), cmd.getArgs());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private static void printArgs(Cmd cmd) {
        Log.o("main class: " + cmd.getMainClass());
        Log.o("args: " + cmd.getArgs().toString());
    }
}
