/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package write.your.own.jvm;

import org.junit.jupiter.api.Test;

class MainTest {
    @Test
    void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
